env:
  es6: true
  browser: true
  commonjs: true
  jest: true

extends: ['htmlacademy/es6', 'plugin:react/recommended']

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 6
  sourceType: module

plugins: ['react', 'import']

settings:
  react:
    version: '16'

"rules": {
  "import/order": [ "error", {
    "alphabetize": {
      order: 'asc',
      caseInsensitive: true
    }
  }],
  "import/newline-after-import": "error"
}
